export const MEMORY_STORE_API_VERSION = 1 as const

export const MEMORY_LIMITS = Object.freeze({
  identityBytes: 256,
  scopeValueBytes: 8_192,
  revisionBytes: 1_024,
})

export const MEMORY_ERROR_CODES = Object.freeze({
  BINDING_REQUIRED: 'MEMORY_BINDING_REQUIRED',
  BINDING_MISMATCH: 'MEMORY_BINDING_MISMATCH',
  INVALID_SCOPE: 'MEMORY_INVALID_SCOPE',
} as const)

export const MEMORY_OPERATION_ERROR_CODES = Object.freeze({
  KIND_MISMATCH: 'MEMORY_STORE_KIND_MISMATCH',
  API_UNSUPPORTED: 'MEMORY_STORE_API_UNSUPPORTED',
  STORE_INVALID: 'MEMORY_STORE_INVALID',
  BINDING_INVALID: 'MEMORY_BINDING_INVALID',
  LOAD_FAILED: 'MEMORY_LOAD_FAILED',
  COMMIT_FAILED: 'MEMORY_COMMIT_FAILED',
  LOAD_TIMEOUT: 'MEMORY_LOAD_TIMEOUT',
  COMMIT_TIMEOUT: 'MEMORY_COMMIT_TIMEOUT',
  COMMIT_OUTCOME_UNKNOWN: 'MEMORY_COMMIT_OUTCOME_UNKNOWN',
  ABORTED: 'RUNTIME_OPERATION_ABORTED',
} as const)
