/** Identity-preserving client view; the root remains the declaration owner. */
export {
  McpClientConnection,
  McpConnectionError,
  McpRemoteToolError,
  connectMcpHttp,
  createMcpHttpClient,
  resolveMcpReconnectOptions,
  type McpAuthenticationKind,
  type McpAuthorizationState,
  type McpCloseReport,
  type McpClientRuntimeOptions,
  type McpClientLifecycleOptions,
  type McpClientState,
  type McpClientStatus,
  type McpHttpClientOptions,
  type McpOAuthCallbackOptions,
  type McpProtocolState,
  type McpReconnectOptions,
  type McpToolResultValue,
  type McpTransportFactory,
  type McpTransportKind,
  type ResolvedMcpReconnectOptions,
} from './index.js'
