export const TOOL_SOURCE_API_VERSION = 1 as const

export const TOOL_SOURCE_LIMITS = Object.freeze({
  sources: 128,
  identityBytes: 256,
  revisionBytes: 256,
  catalogTools: 1_024,
  catalogBytes: 16 * 1024 * 1024,
})

export const TOOL_SOURCE_ERROR_CODES = Object.freeze({
  KIND_MISMATCH: 'TOOL_SOURCE_KIND_MISMATCH',
  API_UNSUPPORTED: 'TOOL_SOURCE_API_UNSUPPORTED',
  ID_CONFLICT: 'TOOL_SOURCE_ID_CONFLICT',
  NAME_CONFLICT: 'TOOL_NAME_CONFLICT',
  SNAPSHOT_INVALID: 'TOOL_SOURCE_SNAPSHOT_INVALID',
  SNAPSHOT_FAILED: 'TOOL_SOURCE_SNAPSHOT_FAILED',
  ABORTED: 'TOOL_SOURCE_SNAPSHOT_ABORTED',
} as const)
