export const CREDENTIAL_CAPABILITY_API_VERSION = 1 as const

export const CREDENTIAL_CAPABILITY_ERROR_CODES = Object.freeze({
  SOURCE_INVALID: 'CREDENTIAL_SOURCE_INVALID',
  STORE_INVALID: 'CREDENTIAL_STORE_INVALID',
} as const)
